version: '3'

services:

  word-api:
    container_name: word-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    #ports:
      #- 8000:8000

networks:
  default:
    external:
      name: mrtimeey